FROM python:3.8-slim

# Set the working directory within the container
WORKDIR /app

# Copy fraud detection component code and any required files
COPY fraud_detection.py /app/
COPY requirements.txt /app/

# Install Python dependencies
RUN pip install -r requirements.txt

CMD ["python", "fraud_detection.py"]